### ISSUE TITLE
Nightclub safe loop does nothing

### ISSUE THREAD

**Issue by RiceWitch** [YimMenu-Lua/Utimate-Menu#2]
tried everything

**Comment by phenibrood** [comment]
> tried everything

In CEO manager menu toggle Start CEO Manager 
Then enable nightclub loop

**Comment by L7NEG** [comment]
> > tried everything
> 
> In CEO manager menu toggle Start CEO Manager Then enable nightclub loop

it seems that there is a bug in lua api not on my side since the loop was fine back in 1.68 so i just removed it in my latest github push for later on to fix it if you have a fix you can just open a pr on here or the one in my profile

**Comment by L7NEG** [comment]
> it seems that there is a bug in lua api not on my side since the loop was fine back in 1.68 so i just removed it in my latest github push for later on to fix it if you have a fix you can just open a pr on here or the one in my profile

it seems that there is a bug in lua api not on my side since the loop was fine back in 1.68 so i just removed it in my latest github push for later on to fix it if you have a fix you can just open a pr on here or the one in my profile
