### ISSUE TITLE
Casino chip exchange

### ISSUE THREAD

**Issue by F1hyy** [YimMenu-Lua/Utimate-Menu#3]
This is more of a suggestion than an issue. Would it be possible to make an option in the casino service category  for no chip exchange limit?

**Comment by L7NEG** [comment]
> This is more of a suggestion than an issue. Would it be possible to make an option in the casino service category for no chip exchange limit?

sure im adding it from kiddions modest menu version of ultimate menu

**Comment by L7NEG** [comment]
> This is more of a suggestion than an issue. Would it be possible to make an option in the casino service category for no chip exchange limit?

Added https://github.com/YimMenu-Lua/Utimate-Menu/commit/88d9a67576e1c712116b36727857a5afc398e33b
