### ISSUE TITLE
Missing credits.

### ISSUE THREAD

**Issue by gir489returns** [YimMenu-Lua/Utimate-Menu#4]
ShinyWasabi has told you multiple times that he does not want his work to be used in your menu you're still using it. I never gave you permission to use Casino Pacino either. Consider this your first and only warning, if it's not removed from the menu, you will be banned from the Lua repository.

**Comment by lonelybud** [comment]
I have used your menu before and considered it as highly standard and respected your work. But seeing now the reality of you copying and pasting other works without asking their permission is unethical but also potentially illegal. If you think they are not respecting your pull requests then you should ask them politely what's wrong with my pr and get the job done with communication. I think you are well educated and will remove their script to avoid problems working with other people and organizations. Thank you.

**Comment by L7NEG** [comment]
> I have used your menu before and considered it as highly standard and respected your work. But seeing now the reality of you copying and pasting other works without asking their permission is unethical but also potentially illegal. If you think they are not respecting your pull requests then you should ask them politely what's wrong with my pr and get the job done with communication. I think you are well educated and will remove their script to avoid problems working with other people and organizations. Thank you.

1st of all i want to be clear that @gir489returns and shinywasabi are already in credits section + i mentioned them into script whoever because of the drama start from him i wont delete it

**Comment by L7NEG** [comment]
s

> ShinyWasabi has told you multiple times that he does not want his work to be used in your menu you're still using it. I never gave you permission to use Casino Pacino either. Consider this your first and only warning, if it's not removed from the menu, you will be banned from the Lua repository.

as long as your or my or anyones work on yimmenu lua repo is open source then its no problem in mentioning credits to all who owns their respective work

**Comment by L7NEG** [comment]
> I have used your menu before and considered it as highly standard and respected your work. But seeing now the reality of you copying and pasting other works without asking their permission is unethical but also potentially illegal. If you think they are not respecting your pull requests then you should ask them politely what's wrong with my pr and get the job done with communication. I think you are well educated and will remove their script to avoid problems working with other people and organizations. Thank you.

i appreciate your feedback unlike the drama started by shinewasabi here https://github.com/L7NEG/Ultimate-Menu/issues/23 + i test every feature on my accs and fixing it one by one

**Comment by lonelybud** [comment]
I think you have admitted that you have added them in credit section and since the code is open source you have copied their code and can update it according to your needs. I should not have interfered here but it is kind a hot in here and i will leave on you guys to communicate the rest.

**Comment by L7NEG** [comment]
> I think you have admitted that you have added them in credit section and since the code is open source you have copied their code and can update it accordingly to your needs. Knowing this I think I should not have interfered in anyone's business and i will leave on you guys to communicate the rest.

Fr bro I swear I didn't add these W features as a skidding + it is only for the users who use this script even they will know that the original code is from ex @gir489returns and shinywasabi so I don't understand why they just trying to insult for no reason
