### ISSUE TITLE
Interferes with teleport, suicide, the basic menu functions of Yim basically.

### ISSUE THREAD

**Issue by TheLegitEz** [YimMenu-Lua/Utimate-Menu#5]
As per the title said.

**Comment by L7NEG** [comment]
> As per the title said.

Could you give me more details on the issue itself it would be great if you can attach a short video of it to know which feature makes it buggy

**Comment by L7NEG** [comment]
from my pov i know fixed it it was cuz of useless codes in the lua file was causing it to be looped i will publish the fix rn
