### ISSUE TITLE
the Tunable options stop work after change session

### ISSUE THREAD

**Issue by coprofago** [YimMenu-Lua/Utimate-Menu#6]
The Tunable options (like rp multiplier) stop work after change session, have to reconfigure again to work again

**Comment by Nukeio** [comment]
Same happens with me in multiple sessions too , also after completing a heist or a job it tends to stop working

**Comment by L7NEG** [comment]
> The Tunable options (like rp multiplier) stop work after change session, have to reconfigure again to work again

That should be normal as you don't want a modded rp multiply like ex 100x rp real value which is only 1x
