### ISSUE TITLE
Code Usage without Explicit Approval

### ISSUE THREAD

**Issue by Yimura** [YimMenu-Lua/Utimate-Menu#7]
@L7NEG, you're making use of Lua code from @gir489returns and @ShinyWasabi.

You may not be familiar with the concept of license rights, so I'll educate you a bit.
Neither gir's nor ShinyWasabi's repositories contain a license, this means that the code can not be used by anyone unless explicit approval is given.

As @shinywasabi and @gir489returns have expressed their discontent on you using their code (even with credits given) and you have since then not taken any action in removing the offending code from your "Ultimate-Menu".

You have 5 days to remove the offending code until further action is taken.

**Comment by L7NEG** [comment]
> @L7NEG, you're making use of Lua code from @gir489returns and @ShinyWasabi.
> 
> You may not be familiar with the concept of license rights, so I'll educate you a bit. Neither gir's nor ShinyWasabi's repositories contain a license, this means that the code can not be used by anyone unless explicit approval is given.
> 
> As @ShinyWasabi and @gir489returns have expressed their discontent on you using their code (even with credits given) and you have since then not taken any action in removing the offending code from your "Ultimate-Menu".
> 
> You have 5 days to remove the offending code until further action is taken.


First thing 
I want just to know 
 what will happen if im not removing these features ?

 2nd thing is that The one who really started it was ShinyWassabi I tried to update his gun van global on his gun van repo script but he didn't merge it instead he closed it as nothing happened same thing happened to a missing global from his daily events script repo

3rd thing can I have full repo edit perms so that I want to fix this repo name and description since it got broke

**Comment by L7NEG** [comment]
> > A github repository which does not contain a License is implicitly “all rights reserved” or “closed license”. So the ONLY way you can legally use it at all is with the consent of the author.
> 
> I didnt know it too.

me too but thats kinda rude from them

**Comment by L7NEG** [comment]
> > @L7NEG, you're making use of Lua code from @gir489returns and @ShinyWasabi.
> > You may not be familiar with the concept of license rights, so I'll educate you a bit. Neither gir's nor ShinyWasabi's repositories contain a license, this means that the code can not be used by anyone unless explicit approval is given.
> > As @ShinyWasabi and @gir489returns have expressed their discontent on you using their code (even with credits given) and you have since then not taken any action in removing the offending code from your "Ultimate-Menu".
> > You have 5 days to remove the offending code until further action is taken.
> 
> First thing I want just to know what will happen if im not removing these features ?
> 
> 2nd thing is that The one who really started it was ShinyWassabi I tried to update his gun van global on his gun van repo script but he didn't merge it instead he closed it as nothing happened same thing happened to a missing global from his daily events script repo
> 
> 3rd thing can I have full repo edit perms so that I want to fix this repo name and description since it got broke

@Yimura

**Comment by L7NEG** [comment]
i removed only useless features and replaced them with the one was in kiddions modest menu so there will be no problems now + credits of both were removed from my work @Yimura

**Comment by L7NEG** [comment]
+ Skidding the gunvan menu from Silent Night Script Is Not Cool Bruh @shinywasabi https://drive.google.com/file/d/1fd94vmLuTNEhHHZWupMS_RARugPic2dt/view?usp=drive_link

**Comment by ShinyWasabi** [comment]
You're such a miserable person. It is obvious that he's the one who skidded it. You can call it from my general coding style in Lua, how old my script is, and more. I don't need to prove anything to a brain-dead like you anyway. It is funny how hard you're trying to tarnish me because you know that your script is nothing without me.

**Comment by L7NEG** [comment]
> You're such a miserable person. It is obvious that he's the one who skidded it. You can call it from my general coding style in Lua, how old my script is, and more. I don't need to prove anything to a brain-dead like you anyway. It is funny how hard you're trying to tarnish me because you know that your script is nothing without me.

Thats The Most Thing That Made Me Laugh Today Lol "your script is nothing without me."
😄 

Bruh Even Without "Your Skidded Codes" It Still No 1 On Modest Menu Scripts Along with Silent Night  

But You Know What Your "Unlock All" Is Nothing Without Me And @Silentsalo xD

**Comment by L7NEG** [comment]
> You're such a miserable person. It is obvious that he's the one who skidded it. You can call it from my general coding style in Lua, how old my script is, and more. I don't need to prove anything to a brain-dead like you anyway. It is funny how hard you're trying to tarnish me because you know that your script is nothing without me.

Your style HUH 
![image](https://github.com/user-attachments/assets/b5ce6548-4685-455f-8831-3c0c18e5f1b3)

Bro Dosent even know it yet

**Comment by L7NEG** [comment]
Yo bro @lhwe Come Check This Drama kid That Have Problems In Their Life xD

**Comment by lhwe** [comment]
> Neither gir's nor ShinyWasabi's repositories contain a license
LMAO TS FUNNY, but @Yimura, if they dont have liscenses, as you said, that means that they are up for grabs as long as credit is given anyways, but the GunVan script is skidded, 100%.

**Comment by L7NEG** [comment]
> > Neither gir's nor ShinyWasabi's repositories contain a license
> 
> LMAO TS FUNNY, but @Yimura, if they dont have liscenses, as you said, that means that they are up for grabs as long as credit is given anyways, but the GunVan script is skidded, 100%.

fr i will just for now listen to yimura but next time i will do something that shinywasabi will be like wickedheis

**Comment by lhwe** [comment]
> > > Neither gir's nor ShinyWasabi's repositories contain a license
> > 
> > LMAO TS FUNNY, but @Yimura, if they dont have liscenses, as you said, that means that they are up for grabs as long as credit is given anyways, but the GunVan script is skidded, 100%.
> 
> fr i will just for now listen to yimura but next time i will do something that shinywasabi will be like wickedheis

🎰🎰🎰
